USE [master]
GO

/****** Object:  Database [aterrizar.com]    Script Date: 18/5/2019 22:14:13 ******/
CREATE DATABASE [aterrizar.com]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'aterrizar.com', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\aterrizar.com.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'aterrizar.com_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\aterrizar.com_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [aterrizar.com] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [aterrizar.com].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [aterrizar.com] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [aterrizar.com] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [aterrizar.com] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [aterrizar.com] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [aterrizar.com] SET ARITHABORT OFF 
GO

ALTER DATABASE [aterrizar.com] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [aterrizar.com] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [aterrizar.com] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [aterrizar.com] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [aterrizar.com] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [aterrizar.com] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [aterrizar.com] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [aterrizar.com] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [aterrizar.com] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [aterrizar.com] SET  DISABLE_BROKER 
GO

ALTER DATABASE [aterrizar.com] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [aterrizar.com] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [aterrizar.com] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [aterrizar.com] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [aterrizar.com] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [aterrizar.com] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [aterrizar.com] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [aterrizar.com] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [aterrizar.com] SET  MULTI_USER 
GO

ALTER DATABASE [aterrizar.com] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [aterrizar.com] SET DB_CHAINING OFF 
GO

ALTER DATABASE [aterrizar.com] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [aterrizar.com] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [aterrizar.com] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [aterrizar.com] SET  READ_WRITE 
GO


